language: node_js
node_js:
  - "11"

services:
  - docker

before_install:
  - npm i omg

script:
  - npx omg build
  - |
    output="$(npx omg run --raw digest -a method=sha1 -a data=foo | tr -d '\n' | tr -d ' ')"
    if [ "$output" != '{"method":"sha1","digest":"0BEEC7B5EA3F0FDBC95D0DD47F3C5BC275DA8A33"}' ] ; then echo "$output"; exit 1; fi
